apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-quarkus-example
spec:
  replicas: 16
  selector:
    matchLabels:
      app: process-quarkus-example
  template:
    metadata:
      labels:
        app: process-quarkus-example
    spec:
      imagePullSecrets:
      - name: private-reg-cred
      containers:
      - name: process-quarkus-example
        image: quay.io/mpaulgreen/process-quarkus-example:15
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "300m"
            memory: 1Gi
          requests:
            cpu: "300m"
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: process-quarkus-example
spec:
  selector:
    app: process-quarkus-example
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080