apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-quarkus-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: process-quarkus-example
  template:
    metadata:
      labels:
        app: process-quarkus-example
    spec:
      imagePullSecrets:
      - name: private-reg-cred
      containers:
      - name: process-quarkus-example
        image: quay.io/mpaulgreen/process-quarkus-example:101
        env:
        - name: MIN_POOL
          value: "10"
        - name: MAX_POOL
          value: "10"
        - name: WORKER_POOL_SIZE
          value: "10"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: process-quarkus-example
spec:
  selector:
    app: process-quarkus-example
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080