---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: a860ebd8381cb5e8805d31ec9ed3d2242e5c5dd9
    app.quarkus.io/build-timestamp: 2021-10-26 - 21:25:15 +0000
  labels:
    app.kubernetes.io/name: kogito-benchmark-client
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: kogito-benchmark-client
spec:
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/name: kogito-benchmark-client
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: a860ebd8381cb5e8805d31ec9ed3d2242e5c5dd9
    app.quarkus.io/build-timestamp: 2021-10-26 - 21:25:15 +0000
  labels:
    app.kubernetes.io/name: kogito-benchmark-client
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: kogito-benchmark-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kogito-benchmark-client
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: a860ebd8381cb5e8805d31ec9ed3d2242e5c5dd9
        app.quarkus.io/build-timestamp: 2021-10-26 - 21:25:15 +0000
      labels:
        app.kubernetes.io/name: kogito-benchmark-client
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      imagePullSecrets:
      - name: private-reg-cred
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/mpaulgreen/kogito-benchmark-client:5
          env:
          - name: URL
            value: http://process-quarkus-example-mpaul-kogito.apps.mpkogito.p9nf.p1.openshiftapps.com
          - name: WORKER_POOL_SIZE
            value: "100"
          imagePullPolicy: Always
          name: kogito-benchmark-client
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP